FROM openjdk:alpine
LABEL maintainer=pascalwhoop
LABEL name=powertac-server

#adding all the needed dependencies, as alpine is a bloody lightweight
RUN apk add --no-cache git maven

#docker usually acts mostly on the root filepath, as it's common for only one process to run inside of a container.
WORKDIR /powertac

#download the server-distribution from github
RUN mkdir data && \
	git clone https://github.com/pascalwhoop/server-distribution


WORKDIR /powertac/server-distribution
COPY settings.xml /root/.m2/
COPY bootstrap-data.xml ./
COPY init.sh ./
COPY server.properties ./
#COPY weather.xml ./

#making a log folder that holds a subfolder with the name of the container content
RUN mkdir -p /log/server-distribution && ln -s /log/server-distribution /powertac/server-distribution/log

EXPOSE 8080 61616
#and start it up
CMD /powertac/server-distribution/init.sh
